### ISSUE TITLE
Running the gpt-structure.py file, an error occurred: NameError: name 'GPT_request' is not defined. But there is no GPT_request method in the original code, what's the situation

### ISSUE THREAD

**Issue by wwwzxxzw** [joonspk-research/generative_agents#161]
Running the gpt-structure.py file, an error occurred: NameError: name 'GPT_request' is not defined. But there is no GPT_request method in the original code, what's the situation

**Comment by wwwzxxzw** [comment]
After executing the Enter option: run 10, the terminal error is as follows:
GNS FUNCTION: <generate_wake_up_hour>
Traceback (most recent call last):
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\reverie.py", line 379, in start_server
    next_tile, pronunciatio, description = persona.move(
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\persona.py", line 222, in move
    plan = self.plan(maze, personas, new_day, retrieved)
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\persona.py", line 148, in plan
    return plan(self, maze, personas, new_day, retrieved)
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\cognitive_modules\plan.py", line 955, in plan
    _long_term_planning(persona, new_day)
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\cognitive_modules\plan.py", line 472, in _long_term_planning
    wake_up_hour = generate_wake_up_hour(persona)
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\cogniive_modules\plan.py", line 38, in generate_wake_up_hour
    return int(run_gpt_prompt_wake_up_hour(persona)[0])
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\promp_template\run_gpt_prompt.py", line 77, in run_gpt_prompt_wake_up_hour
    output = safe_generate_response(prompt, gpt_param, 5, fail_safe,
  File "D:\pycharm2023\Project Location\3、generative_agents-main\reverie\backend_server\persona\promp_template\gpt_structure.py", line 139, in safe_generate_response
    curr_gpt_response = GPT_request(prompt, gpt_parameter)
NameError: name 'GPT_request' is not defined
Error.

**Comment by drudilorenzo** [comment]
Hey, try my fork: https://github.com/drudilorenzo/generative_agents

**Comment by Lee52** [comment]
function GPT_request is now located in the gpt_structure.py
