### ISSUE TITLE
How to modify the proxy of openai

### ISSUE THREAD

**Issue by 765144989** [joonspk-research/generative_agents#54]
How to modify the proxy of openai

**Comment by xcfcode** [comment]
`./generative_agents/reverie/backend_server/persona/prompt_template/gpt_structure.py`
```
openai.api_base = ""
openai.api_key = openai_api_key
```

**Comment by 765144989** [comment]
> `./generative_agents/reverie/backend_server/persona/prompt_template/gpt_structure.py`
> 
> ```
> openai.api_base = ""
> openai.api_key = openai_api_key
> ```
Thanks for your reply, it's correct.

**Comment by 765144989** [comment]
now i have new problem
Traceback (most recent call last):
  File "D:\generative_agents-main\reverie\backend_server\reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "D:\generative_agents-main\reverie\backend_server\reverie.py", line 379, in start_server
    next_tile, pronunciatio, description = persona.move(
  File "D:\generative_agents-main\reverie\backend_server\persona\persona.py", line 220, in move
    perceived = self.perceive(maze)
  File "D:\generative_agents-main\reverie\backend_server\persona\persona.py", line 107, in perceive
    return perceive(self, maze)
  File "D:\generative_agents-main\reverie\backend_server\persona\cognitive_modules\perceive.py", line 144, in perceive
    event_embedding = get_embedding(desc_embedding_in)
  File "D:\generative_agents-main\reverie\backend_server\persona\prompt_template\gpt_structure.py", line 281, in get_embedding
    return openai.Embedding.create(
  File "D:\Program_Files\Anaconda\envs\genagent\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "D:\Program_Files\Anaconda\envs\genagent\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Program_Files\Anaconda\envs\genagent\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\Program_Files\Anaconda\envs\genagent\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "D:\Program_Files\Anaconda\envs\genagent\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
But in my azure there is text-embedding-ada-002 model

**Comment by yaohongfenglove** [comment]
**_To prevent intrusion into the source code_**, it may be more appropriate to make the following changes:

Modify the first few lines of the file **_reverie/backend_server/utils.py .py_** as follows:

```python
import os


# Copy and paste your OpenAI Proxy Endpoint
os.environ["OPENAI_API_BASE"] = "<Your OpenAI Proxy Endpoint>"
# Copy and paste your OpenAI Proxy API Key
openai_api_key = "<Your OpenAI Proxy API>"
# Put your name
...
```
