### ISSUE TITLE
No such file or directory: '../../environment/frontend_server/storage/test-simulation/movement/0.json'

### ISSUE THREAD

**Issue by zhlei07** [joonspk-research/generative_agents#59]
Klaus Mueller persona.scratch.importance_trigger_curr:: 145
150
aldhfoaf/????
the Ville:Dorm for Oak Hill College:Klaus Mueller's room:bed
Traceback (most recent call last):
  File "/Users/zhlei/generative_agents/reverie/backend_server/reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "/Users/zhlei/generative_agents/reverie/backend_server/reverie.py", line 401, in start_server
    with open(curr_move_file, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/test-simulation/movement/0.json'

**Comment by xcfcode** [comment]
`mkdir ./generative_agents/environment/frontend_server/storage/base_the_ville_isabella_maria_klaus/movement` then start the simulation

**Comment by MrElysium** [comment]
add code before File "/Users/zhlei/generative_agents/reverie/backend_server/reverie.py", line 400


``` python
          curr_move_path = f"{sim_folder}/movement"
          # If the folder doesn't exist, we create it.
          if not os.path.exists(curr_move_path):
            os.makedirs(curr_move_path)
```
