### ISSUE TITLE
First time I run the simulation, it shows "Please start the backend first."

### ISSUE THREAD

**Issue by Leon1Wei** [joonspk-research/generative_agents#60]
As title says, I tried over and over again, it still shows Please start the backend first.

**Comment by xcfcode** [comment]
Have you already started the web server via `python manage.py runserver`?

**Comment by SergeyAP** [comment]
Same issue for me.  @xcfcode yes, backend's process is working.
Also I get an issue to backend's log:
`Klaus Mueller persona.scratch.importance_trigger_curr:: 145
150
aldhfoaf/????
the Ville:Dorm for Oak Hill College:Klaus Mueller's room:bed
Traceback (most recent call last):
  File "/Users/zachem/projects/generative_agents/reverie/backend_server/reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "/Users/zachem/projects/generative_agents/reverie/backend_server/reverie.py", line 401, in start_server
    with open(curr_move_file, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/112/movement/0.json'
Error.
`
backend is continue working

Checked on Python3.9 and Python 3.10
MacOS/UbuntuServer22.04

**Comment by SpencerWF** [comment]
Are you running both the frontend and backend on the same computer?



> Same issue for me. @xcfcode yes, backend's process is working. Also I get an issue to backend's log: `Klaus Mueller persona.scratch.importance_trigger_curr:: 145 150 aldhfoaf/???? the Ville:Dorm for Oak Hill College:Klaus Mueller's room:bed Traceback (most recent call last): File "/Users/zachem/projects/generative_agents/reverie/backend_server/reverie.py", line 468, in open_server rs.start_server(int_count) File "/Users/zachem/projects/generative_agents/reverie/backend_server/reverie.py", line 401, in start_server with open(curr_move_file, "w") as outfile: FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/112/movement/0.json' Error. ` backend is continue working
> 
> Checked on Python3.9 and Python 3.10 MacOS/UbuntuServer22.04

This issue is known, and documented in issue #2

**Comment by SergeyAP** [comment]
> Are you running both the frontend and backend on the same computer?
> 
> >

Yes, I've tried that on two VMs and the result is the same

**Comment by SpencerWF** [comment]
Okay, are you sure the VM can access it's own server?  Can you try without the VM? I think it might be that a disconnection between your backend and your frontend is the issue.

**Comment by HananJackie** [comment]
I believe I have the same issue.
everything works up until step 3.

with python 3.10 - the first time I open chrome on http://localhost:8000/simulator_home it shows "Please start the backend first."
with python 3.9 - the first time I open chrome on http://localhost:8000/simulator_home it shows the map and the characters details, without any ability to scale the map. Once I refresh the browser it says "Please start the backend first.".

**Comment by TommyZihao** [comment]
same problem

**Comment by TommyZihao** [comment]
This bug only happens when you run for the first time. To fix this bug, just need to close all terminal, and restart from the `python manage.py runserver`.

**Comment by haoznic** [comment]
i modify the meta.json in storage/ project / reverie/ change the "step" and "curr_time" so the simulation can continue.
i got this problem when i close / reopen my laptop and reopen the browser, then the connection failed, and i stuck here

**Comment by austinmw** [comment]
same issue — any fix?
