### ISSUE TITLE
I'm in china, such a shame we can't normally have an OpenAI API key, but thx for the work!

### ISSUE THREAD

**Issue by zzz6519003** [joonspk-research/generative_agents#7]

**Comment by phonetic112** [comment]
Who asked

**Comment by lp380490944** [comment]
这种小事儿也要提issue，自己想办法搞定啊。感谢的话点个star OK？

**Comment by CarolJia** [comment]
what's your point?

**Comment by 370025263** [comment]
直接去azure代理那边买第三方key就可以

**Comment by happyfire** [comment]
openai.api_base设置一个代理就可以了，代理可以自己搭一个，或者直接第三方付费转发服务

**Comment by SaturnCassini** [comment]
This version runs on GPT4All model which is free and doesn't require a CPU

https://github.com/SaturnCassini/gpt4all_generative_agents

**Comment by PATRICK-1184** [comment]
站起来，裤子都湿了

**Comment by flameleo11** [comment]
虽然说这么提问，看起来不好，没有用
结果还是挺好的，产出了不少有价值的东西
![image](https://github.com/joonspk-research/generative_agents/assets/6859207/8a7e382a-b479-4a3e-b724-cb02147d0c62)

**Comment by 10cl** [comment]
安装Chrome插件ChatDev，看看就行了，兼容了讯飞大模型 https://github.com/10cl/chatdev
访问Github估计也不容易提供 Gitee 的镜像， https://gitee.com/toscl/chatdev

**Comment by daiaji** [comment]
？

**Comment by xionghuyi** [comment]
先把 China 写对，好吗？

**Comment by babytdream** [comment]
Whenever` run xxx `ends, this error will appear. Has anyone encountered this problem?
```
-==- -==- -==- 
Traceback (most recent call last):
  File "/data/generative_agents/reverie/backend_server/reverie.py", line 471, in open_server
    rs.start_server(int_count)
  File "/data/generative_agents/reverie/backend_server/reverie.py", line 379, in start_server
    next_tile, pronunciatio, description = persona.move(
  File "/data/generative_agents/reverie/backend_server/persona/persona.py", line 222, in move
    plan = self.plan(maze, personas, new_day, retrieved)
  File "/data/generative_agents/reverie/backend_server/persona/persona.py", line 148, in plan
    return plan(self, maze, personas, new_day, retrieved)
  File "/data/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 959, in plan
    _determine_action(persona, maze)
  File "/data/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 573, in _determine_action
    generate_task_decomp(persona, act_desp, act_dura))
  File "/data/generative_agents/reverie/backend_server/persona/cognitive_modules/plan.py", line 164, in generate_task_decomp
    return run_gpt_prompt_task_decomp(persona, task, duration)[0]
  File "/data/generative_agents/reverie/backend_server/persona/prompt_template/run_gpt_prompt.py", line 439, in run_gpt_prompt_task_decomp
    output = safe_generate_response(prompt, gpt_param, 5, get_fail_safe(),
  File "/data/generative_agents/reverie/backend_server/persona/prompt_template/gpt_structure.py", line 262, in safe_generate_response
    return func_clean_up(curr_gpt_response, prompt=prompt)
  File "/data/generative_agents/reverie/backend_server/persona/prompt_template/run_gpt_prompt.py", line 378, in __func_clean_up
    duration = int(k[1].split(",")[0].strip())
IndexError: list index out of range
Error.
```

**Comment by botlong** [comment]
I've configured the proxy URL and key, so why is the backend reporting that the token is too long after running?
