### ISSUE TITLE
Buggy, not usable

### ISSUE THREAD

**Issue by pierznj** [joonspk-research/generative_agents#75]
Some issues I have found - overall I have found it unusable:

- instructions don't work unless you copy utils.py to the backend folder
- The front end does not fit on my screen and when I zoom out the simulation environment is cut off
- I enter step n, and do not see anything change in the simulation
- I click on the state of a character and it tells me the character's temperament etc, then when I navigate back it says "Please start the backend first."
- An error appears in the console:
 Traceback (most recent call last):
  File "/Users/pierznewton-john/repos/generative_agents/reverie/backend_server/reverie.py", line 468, in open_server
    rs.start_server(int_count)
  File "/Users/pierznewton-john/repos/generative_agents/reverie/backend_server/reverie.py", line 401, in start_server
    with open(curr_move_file, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '../../environment/frontend_server/storage/test2/movement/0.json'

At this point I realise this is someone's pet project that is in no way ready for anyone else's use.

**Comment by ahmad-alkadri** [comment]
See #59 for the `FileNotFoundError` issue.

Agree with your other points that there needs to be more work done on the frontend.

**Comment by jhalljhall** [comment]
You can create the movement dir in the /frontend_server/storage/<test name>/ and it will add the file.

There is a mention of the ultimate fix in [here](https://github.com/joonspk-research/generative_agents/issues/44)
