### ISSUE TITLE
ERROR: Could not build wheels for gensim, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by izzuddin-noormy** [joonspk-research/generative_agents#94]
Building wheels for collected packages: gensim
  Building wheel for gensim (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/setup.py", line 334, in <module>
          setup(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/.eggs/numpy-1.25.2-py3.9-macosx-10.9-universal2.egg/numpy-1.25.2.dist-info' -> '/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/.eggs/numpy-1.25.2-py3.9-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gensim
  Running setup.py clean for gensim
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/setup.py", line 334, in <module>
          setup(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/dist.py", line 907, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 117, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 125, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/dimsumdin/Work/15.openai/generative_agents/venv/lib/python3.9/site-packages/setuptools/wheel.py", line 171, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/.eggs/numpy-1.25.2-py3.9-macosx-10.9-universal2.egg/numpy-1.25.2.dist-info' -> '/private/var/folders/qw/41ljf22s02l4ctg_2ytrhjk40000gn/T/pip-install-300gw0fh/gensim_bf04eddd7a0146628321cebfe4809c6f/.eggs/numpy-1.25.2-py3.9-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for gensim
Failed to build gensim
ERROR: Could not build wheels for gensim, which is required to install pyproject.toml-based projects
(venv) (base) MacBook-Pro:generative_agents dimsumdin$

**Comment by alric05** [comment]
I have the same issue. Would be nice to have some help

Edit: i fixed it by manually reinstalling gensim and pillow.

**Comment by izzuddin-noormy** [comment]
> pillow

Works with me too, thanks for highlighting that.

**Comment by JYI1998** [comment]
Have you solved this error? I have the same issue

**Comment by GAURAV142004** [comment]
I have the same issue, Can you give the solution for this ?

**Comment by aricupito** [comment]
I had this same issue. For me, after running `pip install gensim --verbose` on Windows terminal, I saw I needed to install [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/), then it worked. Good luck!

**Comment by cloudygoose** [comment]
seems to work when i run
pip install --use-pep517 gensim==3.8.0

**Comment by GavinWhelan** [comment]
I had this same issue and tried making a new venv with python 3.11 instead of python 3.12, and that worked for me

**Comment by alextveit** [comment]
Has anyone gotten it to work fully lately? If so, would anyone be willing to share their files? We are interested in using it as a use case example for Nonprofit & AI community work, and unfortunately have not been able to get it to work on our own yet.

**Comment by shadhinwebtec** [comment]
pip install --use-pep517 gensim==3.8.0
python version 3.9
spacy<3.0.0

That worked for me..

**Comment by yasaswi04** [comment]
try **pip install --use-pep517 gensim==3.8.0** 
This worked for me in **Python-12**.

**Comment by 1202010685** [comment]
> I had this same issue. For me, after running `pip install gensim --verbose` on Windows terminal, I saw I needed to install [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/), then it worked. Good luck!

Hi, I am trying the same way, but failed. There are some sub-choice when I installed the vs_BuildTools.exe, is it my failure due to have wrong choices? Could you please tell me a little bit more about the method?
![image](https://github.com/joonspk-research/generative_agents/assets/73162903/4c0b769c-427d-4696-8e98-76cf78f7c0bc)
